name = "QMLMakie"
uuid = "08f9cac3-3b11-4f1c-9d88-d0e81c500f64"
version = "0.2.0"
authors = ["Steffen Haug <stehau@pm.me>", "Bart Janssens <bart@bartjanssens.org>"]

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"

[sources]
CxxWrap = {path = "../CxxWrap"}
GLMakie = {path = "../pkgdev/Makie/GLMakie"}
QML = {path = "../QML"}

[compat]
CxxWrap = "0.17.3"
GLMakie = "0.13"
ModernGL = "1"
Observables = "0.5"
QML = "0.10.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
